apiVersion: v1
kind: ServiceAccount
metadata:
  name: uniauth
  namespace: uniauth
  labels:
    app.kubernetes.io/name: uniauth
    app.kubernetes.io/component: server
automountServiceAccountToken: false
