apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uniauth.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB }}
  POSTGRES_SERVER: {{ include "uniauth.fullname" . }}-db
  ACCESS_TOKEN_EXPIRE_MINUTES: "{{ .Values.env.ACCESS_TOKEN_EXPIRE_MINUTES }}"
  REDIS_HOST: {{ include "uniauth.fullname" . }}-redis
  REDIS_PORT: "{{ .Values.env.REDIS_PORT }}"
  REDIS_DB: "{{ .Values.env.REDIS_DB }}"
