apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uniauth.fullname" . }}-web
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "uniauth.fullname" . }}-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "uniauth.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "uniauth.fullname" . }}-web
    spec:
      containers:
        - name: uniauth-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_SERVER
              value: {{ .Values.env.POSTGRES_SERVER }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "uniauth.fullname" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uniauth.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "uniauth.fullname" . }}-secret
                  key: SECRET_KEY
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "{{ .Values.env.ACCESS_TOKEN_EXPIRE_MINUTES }}"
            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST }}
            - name: REDIS_PORT
              value: "{{ .Values.env.REDIS_PORT }}"
            - name: REDIS_DB
              value: "{{ .Values.env.REDIS_DB }}"
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
