{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uniauth.fullname" . }}-db
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "uniauth.fullname" . }}-db
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "uniauth.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "uniauth.fullname" . }}-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "uniauth.fullname" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uniauth.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu }}
              memory: {{ .Values.postgres.resources.limits.memory }}
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu }}
              memory: {{ .Values.postgres.resources.requests.memory }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "uniauth.fullname" . }}-postgres-pvc
{{- end }}
