{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uniauth.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "uniauth.fullname" . }}-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None
{{- end }}
