# redis-sentinel-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: uniauth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
        - name: redis-sentinel
          image: redis:7-alpine
          command: ["redis-server", "/redis/sentinel.conf", "--sentinel"]
          ports:
            - containerPort: 26379
          volumeMounts:
            - name: sentinel-config
              mountPath: /redis
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: sentinel-config
          configMap:
            name: redis-sentinel-config
